version: '3.8'
services:
  mongodb:
    image: mongo:5.0
    ports:
      - '27017:27017'
  backend:
    build:
      context: ./backend
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    environment:
      QUARKUS_MONGODB_CONNECTION_STRING: ${QUARKUS_MONGODB_CONNECTION_STRING}
      CORS_ORIGINS: ${CORS_ORIGINS}
      QUARKUS_PROFILE: ${QUARKUS_PROFILE}
      MESHY_API_KEY: ${MESHY_API_KEY}
  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_URL: ${BACKEND_URL}
        PRIMOS_COLLECTION: ${REACT_APP_PRIMOS_COLLECTION}
        REACT_APP_FEE_WALLET: ${REACT_APP_FEE_WALLET}
    ports:
      - '3000:3000'
    depends_on:
      - backend

