envVarGroups:
  - name: primos-env
    envVars:
      - key: BACKEND_URL
        value: ${BACKEND_URL}
      - key: REACT_APP_BACKEND_URL
        value: ${REACT_APP_BACKEND_URL}
      - key: CORS_ORIGINS
        value: ${CORS_ORIGINS}
      - key: REACT_APP_PRIMOS_COLLECTION
        value: ${REACT_APP_PRIMOS_COLLECTION}
      - key: REACT_APP_MAGICEDEN_BASE
        value: ${REACT_APP_MAGICEDEN_BASE}
      - key: REACT_APP_HELIUS_API_KEY
        value: ${REACT_APP_HELIUS_API_KEY}
      - key: MAGICEDEN_API_KEY
        value: ${MAGICEDEN_API_KEY}
      - key: QUARKUS_PROFILE
        value: ${QUARKUS_PROFILE}
      - key: QUARKUS_MONGODB_CONNECTION_STRING
        value: ${QUARKUS_MONGODB_CONNECTION_STRING}
      - key: REACT_APP_COINGECKO_API_KEY
        value: ${REACT_APP_COINGECKO_API_KEY}

services:
  - type: web
    name: primos-marketplace
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - fromGroup: primos-env
      - key: PORT
        value: "8080"
