envVarGroups:
  - name: primos-test
    envVars:
      - key: QUARKUS_MONGODB_CONNECTION_STRING
        value: mongodb+srv://<db_username>:<db_password>@cluster0.shjpril.mongodb.net/primos-db
services:
  - type: web
    name: primos-marketplace
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - fromGroup: primos-test
      - key: BACKEND_URL
        value: https://primos-marketplace.onrender.com
      - key: CORS_ORIGINS
        value: https://primos-marketplace.vercel.app
      - key: QUARKUS_PROFILE
        value: test
