envVarGroups:
  - name: primos-test
    envVars:
      - key: QUARKUS_MONGODB_CONNECTION_STRING
        value: mongodb+srv://primos-client:yiNVTV7b6lHGCePd@cluster0.shjpril.mongodb.net/?authMechanism=SCRAM-SHA-1
services:
  - type: web
    name: primos-marketplace
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - fromGroup: primos-test
      - key: BACKEND_URL
        value: https://primos-marketplace.onrender.com
      - key: REACT_APP_PRIMOS_COLLECTION
        value: primos
      - key: CORS_ORIGINS
        value: https://primos-marketplace.vercel.app
      - key: QUARKUS_PROFILE
        value: test
      - key: PORT
        value: "8080"
